Plume mainnet config
stargate-protocol/stargate-v2 pull request #204
Opened 2024-12-02 19:43 UTC by stgLamps

**In this PR**

- Adding USDC configs for Plume network
- one TODO, filling in Executor address

2024-12-02 20:22 UTC, ravinagill15 reviewed
Looks good! Let's wait to merge until builds pass. I think we also need a changeset?

2024-12-02 20:22 UTC, ravinagill15 commented on packages/stg-evm-v2/devtools/config/mainnet/01/usdc-token.config.ts
> +assert(usdcPlumeAsset.address != null, `External USDC address not found for PLUME`)
nice!

2024-12-02 20:22 UTC, ravinagill15 commented on packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdc.config.ts
Just confirming weth is not needed?

2024-12-02 20:23 UTC, stgLamps commented on packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdc.config.ts
only USDC for Plume for now!

2024-12-02 22:12 UTC, ravinagill15 requested changes

2024-12-02 22:12 UTC, ravinagill15 commented on packages/stg-definitions-v2/src/constant.ts
> +        },
Need to encapsulate this within `safeConfig`

```suggestion
        safeConfig: {
            safeAddress: '0x30b1Ca299577f70bc456Fa37C6822d9088069d31',
            safeUrl: 'https://plume-tx.lzdevnet.org/',
            contractNetworks: {
                [98865]: {
                    multiSendAddress: '0x1E999A606771577f10AFee9111b6263cCF176a1D',
                    multiSendCallOnlyAddress: '0x3BE538f8E6a8809892a1a9618bda69C518a14a8a',
                    safeMasterCopyAddress: '0xB79F7E683E365E21B150812b86f1e0D60512D168',
                    safeProxyFactoryAddress: '0x73aFaC05744f1246Ac94d5Ee92d56be5a7298ecC',
                    fallbackHandlerAddress: '0x1B01E51e3ff9D83DD245D8320c5007b6a3dBF91c',
                    createCallAddress: '0xF83E45c8575b7317686d4bbeE489bB6a93E6C4E3',
                    signMessageLibAddress: '0x34A62CbF94d5dF170CA67C4ECB335453117d4515',
                    simulateTxAccessorAddress: '0x9D59A44Ae2BF3A5A9751463BD4EC77b172eFa9B0',
                },
            },
        },
```

2024-12-03 00:45 UTC, ravinagill15 approved these changes

2024-12-03 00:45 UTC, merged